### ISSUE TITLE
Grace Graph Processing vs Grace Graph Database

### ISSUE THREAD

**Issue by pefi1011** [FreePeter/BlockGRACE#1]
Hi Wenlei,

I'm a bit confused about Grace. I have found

- Grace as graph processing platform, i.e. paper called _Asynchronous Large-Scale Graph Processing Made Easy_
- Grace as graph processing platform II, i.e. paper called _Fast Iterative Graph Computation with Block Updates_
- Grace as general graph database, i.e. paper called _Managing Large Graphs on Multi-Cores With Graph Awareness_

How do these two differ? Did they merged into one system or do they just have the name in common?

Thanks in advance for clarifications

**Comment by wenleix** [comment]
Hi Filip,

Thank you so much for the interests in the GRACE work!

These systems have no relations. As you may note, they are developed and published by a totally different groups of researchers, and they just happened to have the same name :).

**Comment by pefi1011** [comment]
Thanks for the prompt reply, Wenlei.

I have edited my questions, so probably you didn't see the change. The Grace from "Asynchronous Large-Scale Graph Processing Made Easy" and the Grace from "Fast Iterative Graph Computation with Block Updates" are the same, right? 

I was confused since the Grace from "Managing Large Graphs on Multi-Cores With Graph Awareness" says it supports both offline and online analysis and includes "Iterative Execution Platform," so I thought Grace from the first two papers was extended.

**Comment by wenleix** [comment]
Yes,  `Asynchronous Large-Scale Graph Processing Made Easy` and `Fast Iterative Graph Computation with Block Updates` are the same system. The new version (the block GRACE) adopted a new programming interface.

The system proposed in `Managing Large Graphs on Multi-Cores With Graph Awareness` has no relations. They just happened to have the same name.

**Comment by pefi1011** [comment]
Thanks for clarifying.
