### ISSUE TITLE
Fault Tolerance Strategy for Distributed Environment

### ISSUE THREAD

**Issue by pefi1011** [FreePeter/BlockGRACE#2]
Hi Wenlei,

The paper _"Asynchronous Large-Scale Graph Processing Made Easy"_ expresses an idea about scaling Grace beyond a single machine.  If so, do you have in mind what fault tolerance strategy will be used? 

Thanks,
Filip

**Comment by wenleix** [comment]
No we didn't work on the distributed version of GRACE. Although a standard checkpoint based fault-tolerance mechanism should work since GRACE still proceeds in iterations and has a global synchronization barrier after each iteration?

**Comment by pefi1011** [comment]
Thanks
